from noun_as_verb.nomlex_representation.nomlex_adaptation.modifications.subcat_not_constraints import \
	get_extra_not_constraints
from noun_as_verb.nomlex_representation.nomlex_adaptation.modifications.subcat_name_typos import get_correct_subcat_type
from noun_as_verb.nomlex_representation.nomlex_adaptation.modifications.subcat_requirements import \
	get_default_requires, get_default_optionals
from noun_as_verb.nomlex_representation.nomlex_adaptation.modifications.nom_type_to_arg_type import \
	get_as_arg_type, get_compatible_args
from noun_as_verb.nomlex_representation.nomlex_adaptation.modifications.arg_renamings import get_argument_renamings
from noun_as_verb.nomlex_representation.nomlex_adaptation.modifications.arg_default_preps import \
	get_default_preps_by_arg
from noun_as_verb.nomlex_representation.nomlex_adaptation.modifications.arg_default_values import get_default_arg_values
from noun_as_verb.nomlex_representation.nomlex_adaptation.modifications.arg_constraints import get_arg_constraints_maps
from noun_as_verb.nomlex_representation.nomlex_adaptation.modifications.arg_properties import get_plural_property, \
	get_controlled_args, get_subjunct_property, get_arg_attributes_property
