from yet_another_verb.arguments_extractor.extractors.constraints_based.nomlex_args_extractor import NomlexArgsExtractor
from yet_another_verb.arguments_extractor.extractors.constraints_based.patterns_args_extractors import VerbPatternsArgsExtractor
from yet_another_verb.arguments_extractor.args_extractor import ArgsExtractor
from yet_another_verb.arguments_extractor.extractors.verb_references_based.verb_references_args_extractor import \
	DependencyArgAVGArgsExtractor
