from yet_another_verb.arguments_extractor.extraction.representation.str_representation import StrRepresentation
from yet_another_verb.arguments_extractor.extraction.representation.parsed_representation import ParsedRepresentation
from yet_another_verb.arguments_extractor.extraction.representation.parsed_str_representation import ParsedStrRepresentation
from yet_another_verb.arguments_extractor.extraction.representation.parsed_tuple_representation import ParsedTupleRepresentation
from yet_another_verb.arguments_extractor.extraction.representation.parsed_odin_mention_representation import ParsedOdinMentionRepresentation
from yet_another_verb.arguments_extractor.extraction.representation.bio_representation import BIORepresentation
