from enum import Enum


class ArgumentProperty(str, Enum):
	UD_RELATIONS = "UD-RELATIONS"
	SUB_UD_RELATIONS = "SUB-UD-RELATIONS"
	U_POSTAGS = "U-POSTAGS"
	POSTAGS = "POSTAGS"
	PREFIXES = "PREFIXES"
	ILLEGAL_PREFIXES = "ILLEGAL-PREFIXES"

	CONTROLLED = "CONTROLLED"
	REQUIRED = "REQUIRED"
	PLURAL = "PLURAL"


ARGUMENT_PROPERTIES = [p for p in ArgumentProperty]
