from enum import Enum


class EntryProperty(str, Enum):
	TYPE = "TYPE"
	ORTH = "ORTH"
	VERB_SUBC = "VERB-SUBC"
	SUBCATS = "SUBCATS"
	SINGULAR_FALSE = "SINGULAR-FALSE"
	NOM_TYPE = "NOM-TYPE"
	FEATURES = "FEATURES"
	NOUN = "NOUN"
	NOUN_SUBC = "NOUN-SUBC"
	SUBJ_ATTRIBUTE = "SUBJ-ATTRIBUTE"
	OBJ_ATTRIBUTE = "OBJ-ATTRIBUTE"
	IND_OBJ_ATTRIBUTE = "IND-OBJ-ATTRIBUTE"
	SEMI_AUTOMATIC = "SEMI-AUTOMATIC"
	PLURAL_FREQ = "PLURAL-FREQ"
	VERB_SUBJ = "VERB-SUBJ"
	N_N_MOD_NO_OTHER_OBJ = "N-N-MOD-NO-OTHER-OBJ"
	DET_POSS_NO_OTHER_OBJ = "DET-POSS-NO-OTHER-OBJ"

	NOM = "NOM"
	VERB = "VERB"
	PLURAL = "PLURAL"
	HAS_ANOTHER_ENTRY = "HAS-ANOTHER-ENTRY"  # does another entry with the same orth exist?


ENTRY_PROPERTIES = {p for p in EntryProperty}
